permalink: /log/:title/
relative_permalinks: false
markdown: kramdown
timezone: America/Edmonton
exclude: [.gitignore, .editorconfig, Gemfile, Gemfile.lock, README.md, 'sass']

name: Kaleido Family Arts Festival
url: http://kaleidofest.ca
description: "The Kaleido Festival is organized by The Arts on the Ave Edmonton Society, a non-profit, community based, grassroots initiative engaged in development of 118th Avenue into a community arts district."
assets: /assets/
uploads: /uploads/

gems:
  - jekyll-redirect-from

prose:
  siteurl: http://kaleidofest.ca
  media: uploads
