permalink: /log/:title/
relative_permalinks: false
markdown: rdiscount
timezone: America/Edmonton
exclude: [.gitignore, .editorconfig, Gemfile, Gemfile.lock, README.md, assets/sass]

name: Kaleido Family Arts Festival
url: http://kaleidofest.ca
descripiton: Kaleido Family Arts Festival
assets: /assets/
uploads: /uploads/

prose:
  siteurl: http://kaleidofest.ca
  media: /uploads/
